version: '3.8'
services:
  db:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes: 
      - hub-starter-mint:/var/lib/postgresql/data
volumes:
  hub-starter-mint: